# -*- coding: utf-8 -*-
"""Anomaly_detection_using_Autoencoder_and_VAE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16yydI2pRoRQKamJuwRKZTMnJiOgJPIPT
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load your dataset (replace 'your_dataset.csv' with the actual path)
data = pd.read_csv('network_dataset_labeled.csv')
data = data.drop('timestamp', axis=1)
# Preprocess the dataset (scale numerical values)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(data)  # Assumes all columns are numeric

"""# Autoencoder"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras import Model, Input
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

class AutoencoderAnomalyDetector:
    def __init__(self, encoding_dim=10, epochs=50, batch_size=64):
        """
        Initialize the Autoencoder model for anomaly detection.

        Parameters:
        - encoding_dim: Dimension of the encoding layer.
        - epochs: Number of epochs for training.
        - batch_size: Batch size for training.
        """
        self.encoding_dim = encoding_dim
        self.epochs = epochs
        self.batch_size = batch_size
        self.autoencoder = None
        self.X_train = None
        self.X_test = None
        self.threshold = None
        self.anomalies = None

    def preprocess_data(self, data):
        """
        Preprocess the data by scaling and splitting it into train/test sets.

        Parameters:
        - data: The dataset to preprocess.

        Returns:
        - Scaled train and test sets.
        """
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(data)
        self.X_train, self.X_test = train_test_split(X_scaled, test_size=0.2, random_state=42)
        return self.X_train, self.X_test

    def build_autoencoder(self, input_dim):
        """
        Build and compile the Autoencoder model.

        Parameters:
        - input_dim: The number of features in the dataset.
        """
        input_layer = Input(shape=(input_dim,))
        encoded = Dense(self.encoding_dim, activation='relu')(input_layer)
        decoded = Dense(input_dim, activation='sigmoid')(encoded)

        self.autoencoder = Model(input_layer, decoded)
        self.autoencoder.compile(optimizer=Adam(), loss='mean_squared_error')

    def train_autoencoder(self):
        """
        Train the Autoencoder model on the training data.
        """
        self.autoencoder.fit(self.X_train, self.X_train,
                             epochs=self.epochs,
                             batch_size=self.batch_size,
                             validation_data=(self.X_test, self.X_test))

    def predict_reconstruction_error(self):
        """
        Predict the reconstruction error for the test data.

        Returns:
        - Reconstruction error for each sample in the test set.
        """
        reconstructed = self.autoencoder.predict(self.X_test)
        mse = np.mean(np.square(self.X_test - reconstructed), axis=1)
        return mse

    def detect_anomalies(self, mse, percentile=95):
        """
        Detect anomalies based on reconstruction error.

        Parameters:
        - mse: Mean Squared Error (reconstruction error) for each sample.
        - percentile: Threshold percentile for detecting anomalies.

        Returns:
        - Anomaly labels based on the threshold.
        """
        self.threshold = np.percentile(mse, percentile)
        anomalies = mse > self.threshold
        return anomalies

    def visualize_anomalies(self, mse):
        """
        Visualize the reconstruction errors and the anomaly threshold.
        """
        plt.figure(figsize=(10, 6))
        plt.hist(mse, bins=50, alpha=0.6, color='g', label='Reconstruction Error')
        plt.axvline(x=self.threshold, color='r', linestyle='--', label='Anomaly Threshold')
        plt.title("Autoencoder Reconstruction Error for Anomaly Detection")
        plt.legend()
        plt.show()

    def print_anomaly_results(self):
        """
        Print the number of detected anomalies.
        """
        print(f"Number of anomalies detected: {np.sum(self.anomalies)}")

# Initialize the anomaly detection model
anomaly_detector = AutoencoderAnomalyDetector(encoding_dim=10, epochs=50, batch_size=64)

# Load your dataset (replace with your actual data loading code)
data = pd.read_csv('network_dataset_labeled.csv')
data = data.drop('timestamp', axis=1)
# Preprocess the dataset
X_train, X_test = anomaly_detector.preprocess_data(data)

# Build the Autoencoder model
anomaly_detector.build_autoencoder(input_dim=X_train.shape[1])

# Train the Autoencoder model
anomaly_detector.train_autoencoder()

# Calculate reconstruction error
mse = anomaly_detector.predict_reconstruction_error()

# Detect anomalies
anomalies = anomaly_detector.detect_anomalies(mse, percentile=95)

# Visualize the results
anomaly_detector.visualize_anomalies(mse)

# Print the anomaly detection results
anomaly_detector.print_anomaly_results()

# Plot reconstruction error vs actual data
plt.figure(figsize=(10, 6))
plt.scatter(range(len(mse)), mse, c=mse, cmap='viridis', label='Reconstruction Error')
plt.colorbar(label='Reconstruction Error')
plt.title("Reconstruction Error vs. Actual Data")
plt.xlabel("Sample Index")
plt.ylabel("Reconstruction Error")
plt.legend()
plt.show()

"""#"""

# Bar plot of anomaly detection results
anomaly_count = np.sum(anomalies)
normal_count = len(anomalies) - anomaly_count
plt.bar(['Normal', 'Anomalies'], [normal_count, anomaly_count], color=['blue', 'red'])
plt.title("Anomaly Detection Results")
plt.ylabel("Count")
plt.show()

# Plot reconstruction error for multiple features
plt.figure(figsize=(12, 8))
for i in range(X_test.shape[1]):  # loop through features
    plt.plot(range(len(mse)), X_test[:, i], label=f"Feature {i+1}")
plt.title("Reconstruction Error for Multiple Features Over Time")
plt.xlabel("Sample Index")
plt.ylabel("Reconstructed Value")
plt.legend()
plt.show()

# Plot reconstruction error for the first 5 features
plt.figure(figsize=(12, 8))
for i in range(5):  # loop through first 5 features
    plt.plot(range(len(mse)), X_test[:, i], label=f"Feature {i+1}")
plt.title("Reconstruction Error for First 5 Features Over Time")
plt.xlabel("Sample Index")
plt.ylabel("Reconstructed Value")
plt.legend()
plt.show()

"""# Synthetic data"""

# Initialize the anomaly detection model
anomaly_detector = AutoencoderAnomalyDetector(encoding_dim=10, epochs=50, batch_size=64)

# Load your dataset (replace with your actual data loading code)
data = pd.read_csv('anomaly_detection.csv')

# Preprocess the dataset
X_train, X_test = anomaly_detector.preprocess_data(data)

# Build the Autoencoder model
anomaly_detector.build_autoencoder(input_dim=X_train.shape[1])

# Train the Autoencoder model
anomaly_detector.train_autoencoder()

# Calculate reconstruction error
mse = anomaly_detector.predict_reconstruction_error()

# Detect anomalies
anomalies = anomaly_detector.detect_anomalies(mse, percentile=95)

# Visualize the results
anomaly_detector.visualize_anomalies(mse)

# Print the anomaly detection results
anomaly_detector.print_anomaly_results()

"""# On synthetic data 2"""

# Initialize the anomaly detection model
anomaly_detector = AutoencoderAnomalyDetector(encoding_dim=10, epochs=50, batch_size=64)

# Load your dataset (replace with your actual data loading code)
data = pd.read_csv('synthetic_data.csv')
data = data.drop('timestamp', axis=1)
# Preprocess the dataset
X_train, X_test = anomaly_detector.preprocess_data(data)

# Build the Autoencoder model
anomaly_detector.build_autoencoder(input_dim=X_train.shape[1])

# Train the Autoencoder model
anomaly_detector.train_autoencoder()

# Calculate reconstruction error
mse = anomaly_detector.predict_reconstruction_error()

# Detect anomalies
anomalies = anomaly_detector.detect_anomalies(mse, percentile=95)

# Visualize the results
anomaly_detector.visualize_anomalies(mse)

# Print the anomaly detection results
anomaly_detector.print_anomaly_results()

# Initialize the anomaly detection model
anomaly_detector = AutoencoderAnomalyDetector(encoding_dim=10, epochs=50, batch_size=64)

# Load your dataset (replace with your actual data loading code)
data = pd.read_csv('anomaly_combined_dataset.csv')

# Preprocess the dataset
X_train, X_test = anomaly_detector.preprocess_data(data)

# Build the Autoencoder model
anomaly_detector.build_autoencoder(input_dim=X_train.shape[1])

# Train the Autoencoder model
anomaly_detector.train_autoencoder()

# Calculate reconstruction error
mse = anomaly_detector.predict_reconstruction_error()

# Detect anomalies
anomalies = anomaly_detector.detect_anomalies(mse, percentile=95)

# Visualize the results
anomaly_detector.visualize_anomalies(mse)

# Print the anomaly detection results
anomaly_detector.print_anomaly_results()

# Bar plot of anomaly detection results
anomaly_count = np.sum(anomalies)
normal_count = len(anomalies) - anomaly_count
plt.bar(['Normal', 'Anomalies'], [normal_count, anomaly_count], color=['blue', 'red'])
plt.title("Anomaly Detection Results")
plt.ylabel("Count")
plt.show()

