# -*- coding: utf-8 -*-
"""final_GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1muDurebjKu40-2RV-G4VAXC_FJKeeqcG
"""

import numpy as np
from os.path import dirname, abspath
import torch
import torch.nn as nn
import torch.nn.init as init
import os
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

import argparse
import os
import torch
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import warnings
warnings.filterwarnings("ignore")

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import numpy as np

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

def real_data_loading(data_name, seq_len, data):
    """Load and preprocess real-world datasets.

    Args:
      - data_name: dataset name ('network_labelled_dataset')
      - seq_len: sequence length
      - data: dataset (pandas DataFrame)

    Returns:
      - data: preprocessed data.
    """
    assert data_name == 'network_labelled_dataset'

    # Assuming `data` is already loaded as a pandas DataFrame with 20 features.
    # Normalize the data
    scaler = MinMaxScaler()
    ori_data = scaler.fit_transform(data)


    # Preprocess the dataset by cutting data into sequences
    temp_data = []
    for i in range(0, len(ori_data) - seq_len):
        _x = ori_data[i:i + seq_len]
        temp_data.append(_x)

    # Mix the datasets (to make it similar to i.i.d)
    idx = np.random.permutation(len(temp_data))
    data = []
    for i in range(len(temp_data)):
        data.append(temp_data[idx[i]])

    return data

def load_data(opt, data):
    ## Data loading
    if opt.data_name == 'network_labelled_dataset':
        ori_data = real_data_loading(opt.data_name, opt.seq_len, data)  # Pass your dataset here
    print(opt.data_name + ' dataset is ready.')

    return ori_data

# Assuming `network_labelled_dataset` is your pandas DataFrame
# Example of dataset loading
import pandas as pd

# Load your dataset (make sure to adjust the path if necessary)
data = pd.read_csv('/content/nw_data.csv')

# Example options object
class Options:
    data_name = 'network_labelled_dataset'
    seq_len = 30  # For example, using a sequence length of 30

opt = Options()
X=data
# X = data.drop(['timestamp', 'anomaly'], axis=1)

# Load the data
data = load_data(opt, X)

"""# Model"""

import torch
import torch.nn as nn
import torch.nn.init as init

# Weight initialization function
def _weights_init(m):
    classname = m.__class__.__name__
    if isinstance(m, nn.Linear):
        init.xavier_uniform_(m.weight)
        m.bias.data.fill_(0)
    elif classname.find('Conv') != -1:
        m.weight.data.normal_(0.0, 0.02)
    elif classname.find('Norm') != -1:
        m.weight.data.normal_(1.0, 0.02)
        m.bias.data.fill_(0)
    elif classname.find("GRU") != -1:
        for name, param in m.named_parameters():
            if 'weight_ih' in name:
                init.xavier_uniform_(param.data)
            elif 'weight_hh' in name:
                init.orthogonal_(param.data)
            elif 'bias' in name:
                param.data.fill_(0)

# Encoder class
class Encoder(nn.Module):
    """Embedding network between original feature space to latent space.

    Args:
        - input: input time-series features. (L, N, X) = (24, ?, 6)
        - h3: (num_layers, N, H). [3, ?, 24]

    Returns:
        - H: embeddings
    """
    def __init__(self, opt):
        super(Encoder, self).__init__()
        self.rnn = nn.GRU(input_size=opt.z_dim, hidden_size=opt.hidden_dim, num_layers=opt.num_layer)
        self.fc = nn.Linear(opt.hidden_dim, opt.hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        e_outputs, _ = self.rnn(input)
        H = self.fc(e_outputs)
        if sigmoid:
            H = self.sigmoid(H)
        return H

# Recovery class
class Recovery(nn.Module):
    """Recovery network from latent space to original space.

    Args:
        - H: latent representation
        - T: input time information

    Returns:
        - X_tilde: recovered data
    """
    def __init__(self, opt):
        super(Recovery, self).__init__()
        self.rnn = nn.GRU(input_size=opt.hidden_dim, hidden_size=opt.z_dim, num_layers=opt.num_layer)
        self.fc = nn.Linear(opt.z_dim, opt.z_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        r_outputs, _ = self.rnn(input)
        X_tilde = self.fc(r_outputs)
        if sigmoid:
            X_tilde = self.sigmoid(X_tilde)
        return X_tilde

# Generator class
class Generator(nn.Module):
    """Generator function: Generate time-series data in latent space.

    Args:
        - Z: random variables
        - T: input time information

    Returns:
        - E: generated embedding
    """
    def __init__(self, opt):
        super(Generator, self).__init__()
        self.rnn = nn.GRU(input_size=opt.z_dim, hidden_size=opt.hidden_dim, num_layers=opt.num_layer)
        self.fc = nn.Linear(opt.hidden_dim, opt.hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        g_outputs, _ = self.rnn(input)
        E = self.fc(g_outputs)
        if sigmoid:
            E = self.sigmoid(E)
        return E

# Supervisor class
class Supervisor(nn.Module):
    """Generate next sequence using the previous sequence.

    Args:
        - H: latent representation
        - T: input time information

    Returns:
        - S: generated sequence based on the latent representations generated by the generator
    """
    def __init__(self, opt):
        super(Supervisor, self).__init__()
        self.rnn = nn.GRU(input_size=opt.hidden_dim, hidden_size=opt.hidden_dim, num_layers=opt.num_layer)
        self.fc = nn.Linear(opt.hidden_dim, opt.hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        s_outputs, _ = self.rnn(input)
        S = self.fc(s_outputs)
        if sigmoid:
            S = self.sigmoid(S)
        return S

# Discriminator class
class Discriminator(nn.Module):
    """Discriminate the original and synthetic time-series data.

    Args:
        - H: latent representation
        - T: input time information

    Returns:
        - Y_hat: classification results between original and synthetic time-series
    """
    def __init__(self, opt):
        super(Discriminator, self).__init__()
        self.rnn = nn.GRU(input_size=opt.hidden_dim, hidden_size=opt.hidden_dim, num_layers=opt.num_layer)
        self.fc = nn.Linear(opt.hidden_dim, opt.hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        d_outputs, _ = self.rnn(input)
        Y_hat = self.fc(d_outputs)
        if sigmoid:
            Y_hat = self.sigmoid(Y_hat)
        return Y_hat

class Options:
    def __init__(self):
        self.z_dim = 6  # Example z_dim
        self.hidden_dim = 24  # Example hidden_dim
        self.num_layer = 3  # Example num_layer
        # You can add more options here as needed

opt = Options()

# Example of creating the Encoder
encoder = Encoder(opt)

# You can test the forward pass
input_data = torch.randn(10, 24, 6)  # Example input (batch_size=10, seq_len=24, feature_dim=6)
output = encoder(input_data)
print(output.shape)  # Check the output shape

"""# Time GAN"""

# 3. NormMinMax, extract_time, batch_generator, random_generator, Encoder, Recovery, Generator, Discriminator, Supervisor should be implemented or imported here
# Make sure to implement or import those functions and classes for this code to run.

# 4. BaseModel class definition
class BaseModel():
    """ Base Model for timegan
    """

    def __init__(self, opt, ori_data):
        # Seed for deterministic behavior
        self.seed(opt.manualseed)

        # Initialize variables.
        self.opt = opt
        self.ori_data, self.min_val, self.max_val = NormMinMax(ori_data)
        self.ori_time, self.max_seq_len = extract_time(self.ori_data)
        self.data_num, _, _ = np.asarray(ori_data).shape    # 3661; 24; 6
        self.trn_dir = os.path.join(self.opt.outf, self.opt.name, 'train')
        self.tst_dir = os.path.join(self.opt.outf, self.opt.name, 'test')
        self.device = torch.device("cuda:0" if torch.cuda.is_available() and self.opt.device != 'cpu' else "cpu")

    def seed(self, seed_value):
        """ Seed
        Arguments:
            seed_value {int} -- [description]
        """
        # Check if seed is default value
        if seed_value == -1:
            return

        # Otherwise seed all functionality
        random.seed(seed_value)
        torch.manual_seed(seed_value)
        torch.cuda.manual_seed_all(seed_value)
        np.random.seed(seed_value)
        torch.backends.cudnn.deterministic = True

    def save_weights(self, epoch):
        """Save net weights for the current epoch.

        Args:
            epoch ([int]): Current epoch number.
        """
        weight_dir = os.path.join(self.opt.outf, self.opt.name, 'train', 'weights')
        if not os.path.exists(weight_dir):
            os.makedirs(weight_dir)

        torch.save({'epoch': epoch + 1, 'state_dict': self.nete.state_dict()},
                   '%s/netE.pth' % (weight_dir))
        torch.save({'epoch': epoch + 1, 'state_dict': self.netr.state_dict()},
                   '%s/netR.pth' % (weight_dir))
        torch.save({'epoch': epoch + 1, 'state_dict': self.netg.state_dict()},
                   '%s/netG.pth' % (weight_dir))
        torch.save({'epoch': epoch + 1, 'state_dict': self.netd.state_dict()},
                   '%s/netD.pth' % (weight_dir))
        torch.save({'epoch': epoch + 1, 'state_dict': self.nets.state_dict()},
                   '%s/netS.pth' % (weight_dir))

    # Additional methods for training, optimization, etc.

    def train(self):
        """ Train the model
        """
        for iter in range(self.opt.iteration):
            self.train_one_iter_er()

            print('Encoder training step: ' + str(iter) + '/' + str(self.opt.iteration))

        for iter in range(self.opt.iteration):
            self.train_one_iter_s()

            print('Superviser training step: ' + str(iter) + '/' + str(self.opt.iteration))

        for iter in range(self.opt.iteration):
            for kk in range(2):
                self.train_one_iter_g()
                self.train_one_iter_er_()

            self.train_one_iter_d()

            print('Superviser training step: ' + str(iter) + '/' + str(self.opt.iteration))

        self.save_weights(self.opt.iteration)
        self.generated_data = self.generation(self.opt.batch_size)
        print('Finish Synthetic Data Generation')

    #  self.evaluation()

    def generation(self, num_samples, mean=0.0, std=1.0):
        if num_samples == 0:
            return None, None
        self.X0, self.T = batch_generator(self.ori_data, self.ori_time, self.opt.batch_size)
        self.Z = random_generator(num_samples, self.opt.z_dim, self.T, self.max_seq_len, mean, std)
        self.Z = torch.tensor(self.Z, dtype=torch.float32).to(self.device)
        self.E_hat = self.netg(self.Z)  # [?, 24, 24]
        self.H_hat = self.nets(self.E_hat)  # [?, 24, 24]
        generated_data_curr = self.netr(self.H_hat).cpu().detach().numpy()  # [?, 24, 24]

        generated_data = list()
        for i in range(num_samples):
            temp = generated_data_curr[i, :self.ori_time[i], :]
            generated_data.append(temp)

        # Renormalization
        generated_data = generated_data * self.max_val
        generated_data = generated_data + self.min_val
        return generated_data


# 5. TimeGAN class definition
class TimeGAN(BaseModel):
    """TimeGAN Class
    """

    @property
    def name(self):
        return 'TimeGAN'

    def __init__(self, opt, ori_data):
        super(TimeGAN, self).__init__(opt, ori_data)

        # -- Misc attributes
        self.epoch = 0
        self.times = []
        self.total_steps = 0

        # Create and initialize networks.
        self.nete = Encoder(self.opt).to(self.device)
        self.netr = Recovery(self.opt).to(self.device)
        self.netg = Generator(self.opt).to(self.device)
        self.netd = Discriminator(self.opt).to(self.device)
        self.nets = Supervisor(self.opt).to(self.device)

        if self.opt.resume != '':
            print("\nLoading pre-trained networks.")
            self.opt.iter = torch.load(os.path.join(self.opt.resume, 'netG.pth'))['epoch']
            self.nete.load_state_dict(torch.load(os.path.join(self.opt.resume, 'netE.pth'))['state_dict'])
            self.netr.load_state_dict(torch.load(os.path.join(self.opt.resume, 'netR.pth'))['state_dict'])
            self.netg.load_state_dict(torch.load(os.path.join(self.opt.resume, 'netG.pth'))['state_dict'])
            self.netd.load_state_dict(torch.load(os.path.join(self.opt.resume, 'netD.pth'))['state_dict'])
            self.nets.load_state_dict(torch.load(os.path.join(self.opt.resume, 'netS.pth'))['state_dict'])
            print("\tDone.\n")

        # loss
        self.l_mse = nn.MSELoss()
        self.l_r = nn.L1Loss()
        self.l_bce = nn.BCELoss()

        # Setup optimizer
        if self.opt.isTrain:
            self.nete.train()
            self.netr.train()
            self.netg.train()
            self.netd.train()
            self.nets.train()
            self.optimizer_e = optim.Adam(self.nete.parameters(), lr=self.opt.lr, betas=(self.opt.beta1, 0.999))
            self.optimizer_r = optim.Adam(self.netr.parameters(), lr=self.opt.lr, betas=(self.opt.beta1, 0.999))
            self.optimizer_g = optim.Adam(self.netg.parameters(), lr=self.opt.lr, betas=(self.opt.beta1, 0.999))
            self.optimizer_d = optim.Adam(self.netd.parameters(), lr=self.opt.lr, betas=(self.opt.beta1, 0.999))
            self.optimizer_s = optim.Adam(self.nets.parameters(), lr=self.opt.lr, betas=(self.opt.beta1, 0.999))


    # Forward and Backward methods for the TimeGAN class can be included here as well.

"""# Utils"""

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

import argparse
import torch
import os

class Options():
    """Options class

    Returns:
        [argparse]: argparse containing train and test options
    """

    def __init__(self):
        # Inputs for the main function
        self.parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

        # original
        self.parser.add_argument(
            '--data_name',
            choices=['sine', 'stock', 'energy'],
            default='stock',
            type=str)
        self.parser.add_argument(
            '--z_dim',
            help='z or data dimension',
            default=6,
            type=int)
        self.parser.add_argument(
            '--seq_len',
            help='sequence length',
            default=24,
            type=int)
        self.parser.add_argument(
            '--module',
            choices=['gru', 'lstm', 'lstmLN'],
            default='gru',
            type=str)
        self.parser.add_argument(
            '--hidden_dim',
            help='hidden state dimensions (should be optimized)',
            default=24,
            type=int)
        self.parser.add_argument(
            '--num_layer',
            help='number of layers (should be optimized)',
            default=3,
            type=int)
        self.parser.add_argument(
            '--iteration',
            help='Training iterations (should be optimized)',
            default=50000,
            type=int)
        self.parser.add_argument(
            '--batch_size',
            help='the number of samples in mini-batch (should be optimized)',
            default=128,
            type=int)
        self.parser.add_argument(
            '--metric_iteration',
            help='iterations of the metric computation',
            default=10,
            type=int)

        # Add
        self.parser.add_argument('--workers', type=int, help='number of data loading workers', default=8)
        self.parser.add_argument('--device', type=str, default='gpu', help='Device: gpu | cpu')
        self.parser.add_argument('--gpu_ids', type=str, default='0', help='gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU')
        self.parser.add_argument('--ngpu', type=int, default=1, help='number of GPUs to use')
        self.parser.add_argument('--model', type=str, default='TimeGAN', help='chooses which model to use. timegan')

        self.parser.add_argument('--outf', default='./output', help='folder to output images and model checkpoints')
        self.parser.add_argument('--name', type=str, default='experiment_name', help='name of the experiment')

        self.parser.add_argument('--display_server', type=str, default="http://localhost", help='visdom server of the web display')
        self.parser.add_argument('--display_port', type=int, default=8097, help='visdom port of the web display')
        self.parser.add_argument('--display_id', type=int, default=0, help='window id of the web display')
        self.parser.add_argument('--display', action='store_true', help='Use visdom.')

        self.parser.add_argument('--manualseed', default=-1, type=int, help='manual seed')

        # Train
        self.parser.add_argument('--print_freq', type=int, default=1000, help='frequency of showing training results on console')
        self.parser.add_argument('--load_weights', action='store_true', help='Load the pretrained weights')
        self.parser.add_argument('--resume', default='', help="path to checkpoints (to continue training)")

        self.parser.add_argument('--beta1', type=float, default=0.9, help='momentum term of adam')
        self.parser.add_argument('--lr', type=float, default=0.001, help='initial learning rate for adam')

        self.parser.add_argument('--w_gamma', type=float, default=1, help='Gamma weight')
        self.parser.add_argument('--w_es', type=float, default=0.1, help='Encoder loss weight')
        self.parser.add_argument('--w_e0', type=float, default=10, help='Encoder loss weight')
        self.parser.add_argument('--w_g', type=float, default=100, help='Generator loss weight.')
        self.isTrain = True
        self.opt = None

    def parse(self):
        """ Parse Arguments.
        """

        # Simulate argparse in Google Colab with predefined values or default ones
        args = {
            'data_name': 'stock',
            'z_dim': 6,
            'seq_len': 24,
            'module': 'gru',
            'hidden_dim': 24,
            'num_layer': 3,
            'iteration': 50000,
            'batch_size': 128,
            'metric_iteration': 10,
            'workers': 8,
            'device': 'gpu',
            'gpu_ids': '0',
            'ngpu': 1,
            'model': 'TimeGAN',
            'outf': './output',
            'name': 'experiment_name',
            'display_server': 'http://localhost',
            'display_port': 8097,
            'display_id': 0,
            'display': False,
            'manualseed': -1,
            'print_freq': 1000,
            'load_weights': False,
            'resume': '',
            'beta1': 0.9,
            'lr': 0.001,
            'w_gamma': 1,
            'w_es': 0.1,
            'w_e0': 10,
            'w_g': 100
        }

        self.opt = argparse.Namespace(**args)
        self.opt.isTrain = self.isTrain  # train or test

        str_ids = self.opt.gpu_ids.split(',')
        self.opt.gpu_ids = [int(id) for id in str_ids if int(id) >= 0]

        # set gpu ids
        if self.opt.device == 'gpu':
            torch.cuda.set_device(self.opt.gpu_ids[0])

        # save to the disk
        if self.opt.name == 'experiment_name':
            self.opt.name = "%s/%s" % (self.opt.model, self.opt.data_name)
        expr_dir = os.path.join(self.opt.outf, self.opt.name)

        if not os.path.isdir(expr_dir):
            os.makedirs(expr_dir)

        file_name = os.path.join(expr_dir, 'opt.txt')
        with open(file_name, 'wt') as opt_file:
            opt_file.write('------------ Options -------------\n')
            for k, v in sorted(args.items()):
                opt_file.write('%s: %s\n' % (str(k), str(v)))
            opt_file.write('-------------- End ----------------\n')

        return self.opt

# Example usage in Colab:
opt = Options().parse()
print(opt)

!pip install torch torchvision

import argparse
import os
import torch


class Options():
    """Options class

    Returns:
        [argparse]: argparse containing train and test options
    """

    def __init__(self):
        # Inputs for the main function
        self.parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

        # original
        self.parser.add_argument(
            '--data_name',
            choices=['sine', 'stock', 'energy'],
            default='stock',
            type=str)
        self.parser.add_argument(
            '--z_dim',
            help='z or data dimension',
            default=6,
            type=int)
        self.parser.add_argument(
            '--seq_len',
            help='sequence length',
            default=24,
            type=int)
        self.parser.add_argument(
            '--module',
            choices=['gru', 'lstm', 'lstmLN'],
            default='gru',
            type=str)
        self.parser.add_argument(
            '--hidden_dim',
            help='hidden state dimensions (should be optimized)',
            default=24,
            type=int)
        self.parser.add_argument(
            '--num_layer',
            help='number of layers (should be optimized)',
            default=3,
            type=int)
        self.parser.add_argument(
            '--iteration',
            help='Training iterations (should be optimized)',
            default=50000,
            type=int)
        self.parser.add_argument(
            '--batch_size',
            help='the number of samples in mini-batch (should be optimized)',
            default=128,
            type=int)
        self.parser.add_argument(
            '--metric_iteration',
            help='iterations of the metric computation',
            default=10,
            type=int)

        # Add
        self.parser.add_argument('--workers', type=int, help='number of data loading workers', default=8)
        self.parser.add_argument('--device', type=str, default='gpu', help='Device: gpu | cpu')
        self.parser.add_argument('--gpu_ids', type=str, default='0', help='gpu ids: e.g. 0  0,1,2, 0,2. use -1 for CPU')
        self.parser.add_argument('--ngpu', type=int, default=1, help='number of GPUs to use')
        self.parser.add_argument('--model', type=str, default='TimeGAN', help='chooses which model to use. timegan')

        self.parser.add_argument('--outf', default='./output', help='folder to output images and model checkpoints')
        self.parser.add_argument('--name', type=str, default='experiment_name', help='name of the experiment')

        self.parser.add_argument('--display_server', type=str, default="http://localhost", help='visdom server of the web display')
        self.parser.add_argument('--display_port', type=int, default=8097, help='visdom port of the web display')
        self.parser.add_argument('--display_id', type=int, default=0, help='window id of the web display')
        self.parser.add_argument('--display', action='store_true', help='Use visdom.')

        self.parser.add_argument('--manualseed', default=-1, type=int, help='manual seed')

        # Train
        self.parser.add_argument('--print_freq', type=int, default=1000, help='frequency of showing training results on console')
        self.parser.add_argument('--load_weights', action='store_true', help='Load the pretrained weights')
        self.parser.add_argument('--resume', default='', help="path to checkpoints (to continue training)")

        self.parser.add_argument('--beta1', type=float, default=0.9, help='momentum term of adam')
        self.parser.add_argument('--lr', type=float, default=0.001, help='initial learning rate for adam')

        self.parser.add_argument('--w_gamma', type=float, default=1, help='Gamma weight')
        self.parser.add_argument('--w_es', type=float, default=0.1, help='Encoder loss weight')
        self.parser.add_argument('--w_e0', type=float, default=10, help='Encoder loss weight')
        self.parser.add_argument('--w_g', type=float, default=100, help='Generator loss weight.')
        self.isTrain = True
        self.opt = None

    def parse(self):
        """ Parse Arguments.
        """

        self.opt = self.parser.parse_args()
        self.opt.isTrain = self.isTrain  # train or test

        str_ids = self.opt.gpu_ids.split(',')
        self.opt.gpu_ids = []
        for str_id in str_ids:
            id = int(str_id)
            if id >= 0:
                self.opt.gpu_ids.append(id)

        # set gpu ids
        if self.opt.device == 'gpu':
            torch.cuda.set_device(self.opt.gpu_ids[0])

        args = vars(self.opt)

        # save to the disk
        if self.opt.name == 'experiment_name':
            self.opt.name = "%s/%s" % (self.opt.model, self.opt.data_name)
        expr_dir = os.path.join(self.opt.outf, self.opt.name)

        if not os.path.isdir(expr_dir):
            os.makedirs(expr_dir)

        file_name = os.path.join(expr_dir, 'opt.txt')
        with open(file_name, 'wt') as opt_file:
            opt_file.write('------------ Options -------------\n')
            for k, v in sorted(args.items()):
                opt_file.write('%s: %s\n' % (str(k), str(v)))
            opt_file.write('-------------- End ----------------\n')
        return self.opt

import numpy as np


def train_test_divide (data_x, data_x_hat, data_t, data_t_hat, train_rate = 0.8):
  """Divide train and test data for both original and synthetic data.

  Args:
    - data_x: original data
    - data_x_hat: generated data
    - data_t: original time
    - data_t_hat: generated time
    - train_rate: ratio of training data from the original data
  """
  # Divide train/test index (original data)
  no = len(data_x)
  idx = np.random.permutation(no)
  train_idx = idx[:int(no*train_rate)]
  test_idx = idx[int(no*train_rate):]

  train_x = [data_x[i] for i in train_idx]
  test_x = [data_x[i] for i in test_idx]
  train_t = [data_t[i] for i in train_idx]
  test_t = [data_t[i] for i in test_idx]

  # Divide train/test index (synthetic data)
  no = len(data_x_hat)
  idx = np.random.permutation(no)
  train_idx = idx[:int(no*train_rate)]
  test_idx = idx[int(no*train_rate):]

  train_x_hat = [data_x_hat[i] for i in train_idx]
  test_x_hat = [data_x_hat[i] for i in test_idx]
  train_t_hat = [data_t_hat[i] for i in train_idx]
  test_t_hat = [data_t_hat[i] for i in test_idx]

  return train_x, train_x_hat, test_x, test_x_hat, train_t, train_t_hat, test_t, test_t_hat


def extract_time (data):
  """Returns Maximum sequence length and each sequence length.

  Args:
    - data: original data

  Returns:
    - time: extracted time information
    - max_seq_len: maximum sequence length
  """
  time = list()
  max_seq_len = 0
  for i in range(len(data)):
    max_seq_len = max(max_seq_len, len(data[i][:,0]))
    time.append(len(data[i][:,0]))

  return time, max_seq_len


def random_generator (batch_size, z_dim, T_mb, max_seq_len):
  """Random vector generation.

  Args:
    - batch_size: size of the random vector
    - z_dim: dimension of random vector
    - T_mb: time information for the random vector
    - max_seq_len: maximum sequence length

  Returns:
    - Z_mb: generated random vector
  """
  Z_mb = list()
  for i in range(batch_size):
    temp = np.zeros([max_seq_len, z_dim])
    temp_Z = np.random.uniform(0., 1, [T_mb[i], z_dim])
    temp[:T_mb[i],:] = temp_Z
    Z_mb.append(temp_Z)
  return Z_mb


def NormMinMax(data):
    """Min-Max Normalizer.

    Args:
      - data: raw data

    Returns:
      - norm_data: normalized data
      - min_val: minimum values (for renormalization)
      - max_val: maximum values (for renormalization)
    """
    min_val = np.min(np.min(data, axis=0), axis=0)
    data = data - min_val  # [3661, 24, 6]

    max_val = np.max(np.max(data, axis=0), axis=0)
    norm_data = data / (max_val + 1e-7)

    return norm_data, min_val, max_val

"""#Bhandari ji dalo fatafat"""

import numpy as np

def train_test_divide(data_x, data_x_hat, data_t, data_t_hat, train_rate=0.8):
    """Divide train and test data for both original and synthetic data.

    Args:
      - data_x: original data
      - data_x_hat: generated data
      - data_t: original time
      - data_t_hat: generated time
      - train_rate: ratio of training data from the original data
    """
    # Divide train/test index (original data)
    no = len(data_x)
    idx = np.random.permutation(no)
    train_idx = idx[:int(no*train_rate)]
    test_idx = idx[int(no*train_rate):]

    train_x = [data_x[i] for i in train_idx]
    test_x = [data_x[i] for i in test_idx]
    train_t = [data_t[i] for i in train_idx]
    test_t = [data_t[i] for i in test_idx]

    # Divide train/test index (synthetic data)
    no = len(data_x_hat)
    idx = np.random.permutation(no)
    train_idx = idx[:int(no*train_rate)]
    test_idx = idx[int(no*train_rate):]

    train_x_hat = [data_x_hat[i] for i in train_idx]
    test_x_hat = [data_x_hat[i] for i in test_idx]
    train_t_hat = [data_t_hat[i] for i in train_idx]
    test_t_hat = [data_t_hat[i] for i in test_idx]

    return train_x, train_x_hat, test_x, test_x_hat, train_t, train_t_hat, test_t, test_t_hat


def extract_time(data):
    """Returns Maximum sequence length and each sequence length.

    Args:
      - data: original data

    Returns:
      - time: extracted time information
      - max_seq_len: maximum sequence length
    """
    time = list()
    max_seq_len = 0
    for i in range(len(data)):
        max_seq_len = max(max_seq_len, len(data[i][:, 0]))
        time.append(len(data[i][:, 0]))

    return time, max_seq_len


def random_generator(batch_size, z_dim, T_mb, max_seq_len):
    """Random vector generation.

    Args:
      - batch_size: size of the random vector
      - z_dim: dimension of random vector
      - T_mb: time information for the random vector
      - max_seq_len: maximum sequence length

    Returns:
      - Z_mb: generated random vector
    """
    Z_mb = list()
    for i in range(batch_size):
        temp = np.zeros([max_seq_len, z_dim])
        temp_Z = np.random.uniform(0., 1, [T_mb[i], z_dim])
        temp[:T_mb[i], :] = temp_Z
        Z_mb.append(temp_Z)
    return Z_mb


def NormMinMax(data):
    """Min-Max Normalizer.

    Args:
      - data: raw data

    Returns:
      - norm_data: normalized data
      - min_val: minimum values (for renormalization)
      - max_val: maximum values (for renormalization)
    """
    min_val = np.min(np.min(data, axis=0), axis=0)
    data = data - min_val  # [3661, 24, 6]

    max_val = np.max(np.max(data, axis=0), axis=0)
    norm_data = data / (max_val + 1e-7)

    return norm_data, min_val, max_val

"""# Training"""

def train():
    """ Training
    """

    # ARGUMENTS
    opt = Options().parse()

    # LOAD DATA
    ori_data = load_data(opt)

    # LOAD MODEL
    model = TimeGAN(opt, ori_data)

    # TRAIN MODEL
    model.train()

# if __name__ == '__main__':
    # train()

import sys

def train():
    """ Training
    """

    # ARGUMENTS
    try:
        opt = Options().parse()
    except SystemExit as e:
        print(f"An error occurred during argument parsing: {e}")
        # This helps to see the argparse error message
        sys.exit(e.code)  # Exit with the original error code if needed.

    # LOAD DATA
    ori_data = load_data(opt)

    # LOAD MODEL
    model = TimeGAN(opt, ori_data)

    # TRAIN MODEL
    model.train()

if __name__ == '__main__':
    train()

