# -*- coding: utf-8 -*-
"""GAN_Data_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C3PshFM9tG02yZ2EypCev9GyaNLk8ff9
"""

pip install numpy pandas tensorflow

import numpy as np
import pandas as pd

# Example: Load a time-series dataset
# Replace this with your time-series data
df = pd.read_csv('network_dataset_labeled.csv')
# Normalize the data
# data = (df - df.mean()) / df.std()

# # Reshape into 3D format (samples, sequence length, features)
# sequence_length = 30  # Example sequence length
# data_np = data.values
# num_samples = len(data_np) - sequence_length + 1

# # Create overlapping sequences
# time_series_data = np.array([data_np[i:i+sequence_length] for i in range(num_samples)])
# print("Time-series data shape:", time_series_data.shape)

print(df.dtypes)

df['timestamp']

df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

df.head(10)

df.isnull().sum()

df = df.dropna()

# Compute mean and standard deviation
mean = df.mean()
std = df.std()

# Display results
print("Mean:\n", mean)
print("Standard Deviation:\n", std)

# Combine mean and std into a single DataFrame
stats_df = pd.DataFrame({'mean': mean, 'std': std})

# Save to CSV
stats_df.to_csv('stats.csv', index=True)

print("Statistics saved to stats.csv")





data = (df - df.mean()) / df.std()

data.head(10)

df.drop('bandwidth', axis=1, inplace=True)

df.drop('Network measure', axis=1, inplace=True)

sequence_length = 30  # Example sequence length
data_np = data.values
num_samples = len(data_np) - sequence_length + 1

# Create overlapping sequences
time_series_data = np.array([data_np[i:i+sequence_length] for i in range(num_samples)])
print("Time-series data shape:", time_series_data.shape)

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, LSTM, GRU, Dropout, Softmax
from tensorflow.keras.optimizers import Adam
import numpy as np

class TimeGAN:
    def __init__(self, seq_length, num_features, categorical_features=None, hidden_dim=24, z_dim=16, lr=0.001):
        """
        TimeGAN model class.

        Parameters:
        - seq_length: Length of the input sequence.
        - num_features: Total number of features (numerical + categorical).
        - categorical_features: List of indices of categorical features.
        - hidden_dim: Number of hidden units in the LSTM layers.
        - z_dim: Dimensionality of the latent space.
        - lr: Learning rate for the optimizer.
        """
        self.seq_length = seq_length
        self.num_features = num_features
        self.categorical_features = categorical_features or []
        self.num_numerical = num_features - len(self.categorical_features)
        self.hidden_dim = hidden_dim
        self.z_dim = z_dim
        self.lr = lr

    def build_generator(self):
        """
        Build the Generator network.
        """
        input_noise = Input(shape=(self.seq_length, self.z_dim))
        x = LSTM(self.hidden_dim, return_sequences=True)(input_noise)
        x = Dropout(0.2)(x)

        # Output layers for numerical and categorical features
        numerical_output = Dense(self.num_numerical)(x)

        categorical_outputs = []
        for _ in self.categorical_features:
            categorical_outputs.append(Dense(1, activation='softmax')(x))

        output = [numerical_output] + categorical_outputs
        return Model(inputs=input_noise, outputs=output, name="Generator")

    def build_discriminator(self):
        """
        Build the Discriminator network.
        """
        input_data = Input(shape=(self.seq_length, self.num_features))
        x = LSTM(self.hidden_dim, return_sequences=False)(input_data)
        x = Dropout(0.2)(x)
        output = Dense(1, activation='sigmoid')(x)
        return Model(inputs=input_data, outputs=output, name="Discriminator")

    def build_embedder(self):
        """
        Build the Embedder network.
        """
        input_data = Input(shape=(self.seq_length, self.num_features))
        x = LSTM(self.hidden_dim, return_sequences=True)(input_data)
        output = Dense(self.hidden_dim)(x)
        return Model(inputs=input_data, outputs=output, name="Embedder")

    def build_recovery(self):
        """
        Build the Recovery network.
        """
        input_embed = Input(shape=(self.seq_length, self.hidden_dim))
        x = LSTM(self.hidden_dim, return_sequences=True)(input_embed)
        output = Dense(self.num_features)(x)
        return Model(inputs=input_embed, outputs=output, name="Recovery")

    def compile_models(self):
        """
        Compile all models with optimizers and loss functions.
        """
        self.generator = self.build_generator()
        self.discriminator = self.build_discriminator()
        self.embedder = self.build_embedder()
        self.recovery = self.build_recovery()

        # Optimizers
        self.optimizer = Adam(learning_rate=self.lr)

        # Compile models (add custom training later)
        self.discriminator.compile(optimizer=self.optimizer, loss='binary_crossentropy', metrics=['accuracy'])
        self.embedder.compile(optimizer=self.optimizer, loss='mse')
        self.recovery.compile(optimizer=self.optimizer, loss='mse')

    def train(self, real_data, epochs=1000, batch_size=64):
        """
        Train the TimeGAN model.

        Parameters:
        - real_data: The real time-series data.
        - epochs: Number of training epochs.
        - batch_size: Batch size for training.
        """
        # Prepare training data
        real_labels = np.ones((batch_size, 1))
        fake_labels = np.zeros((batch_size, 1))

        for epoch in range(epochs):
            # Sample real data
            idx = np.random.randint(0, real_data.shape[0], batch_size)
            real_batch = real_data[idx]

            # Generate synthetic data
            noise = np.random.normal(0, 1, (batch_size, self.seq_length, self.z_dim))
            fake_batches = self.generator.predict(noise)

            # Separate numerical and categorical features
            fake_batch = np.concatenate([fake_batches[0]] +
                                         [np.argmax(fb, axis=-1) for fb in fake_batches[1:]], axis=-1)

            # Train Discriminator
            d_loss_real = self.discriminator.train_on_batch(real_batch, real_labels)
            d_loss_fake = self.discriminator.train_on_batch(fake_batch, fake_labels)
            d_loss = 0.5 * np.add(d_loss_real, d_loss_fake)

            # Train Generator (via adversarial feedback)
            g_loss = self.discriminator.train_on_batch(fake_batch, real_labels)

            # Print progress
            if epoch % 100 == 0:
                print(f"Epoch {epoch} | D Loss: {d_loss[0]:.4f}, Acc: {d_loss[1]:.4f} | G Loss: {g_loss:.4f}")

    def generate_synthetic_data(self, num_samples):
        """
        Generate synthetic time-series data using the Generator.

        Parameters:
        - num_samples: Number of samples to generate.
        """
        noise = np.random.normal(0, 1, (num_samples, self.seq_length, self.z_dim))
        synthetic_batches = self.generator.predict(noise)

        # Combine numerical and categorical outputs
        synthetic_data = np.concatenate([synthetic_batches[0]] +
                                         [np.argmax(sb, axis=-1) for sb in synthetic_batches[1:]], axis=-1)
        return synthetic_data

# Placeholder for training
# Load your implementation or library
gan = TimeGAN(seq_length=sequence_length, num_features=data.shape[1])

generator = gan.build_generator()
print(generator.summary())

z_samples = np.random.normal(size=(num_samples, sequence_length, gan.z_dim))
synthetic_data = generator.predict(z_samples)

print("Synthetic data shape:", synthetic_data.shape)

import matplotlib.pyplot as plt

# Example: Visualize a few original and synthetic sequences
plt.plot(time_series_data[0, :, 0], label='Original')
plt.plot(synthetic_data[0, :, 0], label='Synthetic')
plt.legend()
plt.show()

#printing synthetic data
print(synthetic_data)

synthetic_data.shape

# Flatten the synthetic time-series data
num_features = synthetic_data.shape[2]
synthetic_data_2d = synthetic_data.reshape(-1, num_features)

print("Synthetic data shape (2D):", synthetic_data_2d.shape)

# Denormalize the 2D synthetic data
original_scale_data = synthetic_data_2d * std.values + mean.values

print("De-normalized data shape:", original_scale_data.shape)

original_scale_data = pd.DataFrame(original_scale_data, columns=data.columns)

original_scale_data.head(10)

original_scale_data.shape

original_scale_data.to_csv("synthetic_data.csv", index=False)

df1 = pd.read_csv('network_dataset_labeled.csv')
df1['timestamp'] = pd.to_datetime(df1['timestamp'], errors='coerce')
df1.drop(['bandwidth', 'Network measure'], axis=1, inplace=True)

df1.columns

import matplotlib.pyplot as plt
import seaborn as sns

features = ['timestamp', 'throughput', 'congestion', 'packet_loss', 'latency',
       'jitter', 'Routers', 'Planned route', 'Network target',
       'Percentage video occupancy', 'Bitrate video', 'Number videos',
       'anomaly_throughput', 'anomaly_congestion', 'anomaly_packet_loss',
       'anomaly_latency', 'anomaly_jitter', 'anomaly']

def plot_side_by_side_histograms(original_data, synthetic_data, features):
    for feature in features:
        # Create subplots
        fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

        # Original Data
        sns.histplot(original_data[feature], color="blue", kde=True, stat="density", bins=30, ax=axes[0])
        axes[0].set_title(f"Original {feature}")
        axes[0].set_xlabel(feature)
        axes[0].set_ylabel("Density")

        # Synthetic Data
        sns.histplot(synthetic_data[feature], color="orange", kde=True, stat="density", bins=30, ax=axes[1])
        axes[1].set_title(f"Synthetic {feature}")
        axes[1].set_xlabel(feature)

        # Overall figure title
        fig.suptitle(f"Histogram Comparison: {feature}", fontsize=16)
        plt.tight_layout()
        plt.show()

plot_side_by_side_histograms(df1, original_scale_data, features)

